### PR TITLE
Use fake info

### PR DESCRIPTION
**Pull request by ocefpaf**
@rsignell-usgs I believe we should have done this a long time ago.

### CODE REVIEW

**Comment by ocefpaf** [comment]
This one is ready for review.

Now a bad yaml will raise a more detailed traceback adn error message that will make it easier to debug the issue. For example:

```python
Traceback (most recent call last):
  File "/home/filipe/miniconda3/envs/YAML2NCML/lib/python3.5/site-packages/yaml2ncml/yaml2ncml.py", line 40, in str_att
    value = ','.join(value)
TypeError: sequence item 1: expected str instance, CommentedMap found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/filipe/miniconda3/envs/YAML2NCML/bin/yaml2ncml", line 11, in <module>
    sys.exit(main())
  File "/home/filipe/miniconda3/envs/YAML2NCML/lib/python3.5/site-packages/yaml2ncml/yaml2ncml.py", line 254, in main
    text = build(yml)
  File "/home/filipe/miniconda3/envs/YAML2NCML/lib/python3.5/site-packages/yaml2ncml/yaml2ncml.py", line 237, in build
    text = add_global_atts(text, yml)
  File "/home/filipe/miniconda3/envs/YAML2NCML/lib/python3.5/site-packages/yaml2ncml/yaml2ncml.py", line 66, in add_global_atts
    text += str_att(key, value)
  File "/home/filipe/miniconda3/envs/YAML2NCML/lib/python3.5/site-packages/yaml2ncml/yaml2ncml.py", line 42, in str_att
    raise ValueError('Expected `str` got {!r}'.format(value)) from e
ValueError: Expected `str` got ['https://woodshole.er.usgs.gov/operations/modeling/COAWST', CommentedMap([('DOI', '10.1002/2014GL061357')])]
```

You can see quickly that the `DOI` was interpreted as another field instead of a single value due to the extra space after the `:`.

**Comment by ocefpaf** [comment]
Argh! Python 2.7 is holding us back :unamused: 

```
E     File "/home/travis/miniconda/envs/TEST/lib/python2.7/site-packages/yaml2ncml/yaml2ncml.py", line 42
E       raise ValueError('Expected `str` got {!r}'.format(value)) from e
E                                                                    ^
E   SyntaxError: invalid syntax
```

**Comment by rsignell-usgs** [comment]
@ocefpaf , seems like this one still should be merged, right?

**Comment by ocefpaf** [comment]
> @ocefpaf , seems like this one still should be merged, right?

IMO yes.

**Pull request merged**
