### PR TITLE
corrected tests to have CF v48 names

### PR DESCRIPTION
**Pull request by zdefne-usgs**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@zdefne-usgs and @rsignell-usgs we should probably write a thin wrapper to the multiple versions of the CF names and use the version as input when writing the ncml. Does that make sense? Would that be worth the effort?

**Comment by rsignell-usgs** [comment]
@ocefpaf do you mean actually read the standard name list xml file and use that somehow?

**Comment by ocefpaf** [comment]
> @ocefpaf do you mean actually read the standard name xml file (e.g. http://cfconventions.org/Data/cf-standard-names/48/src/cf-standard-name-table.xml) and use that somehow?

Exactly. Just not sure if that is worth the effort and how difficult that would be to implement.

**Comment by rsignell-usgs** [comment]
We should probably raise this as an issue instead of discussing in this PR, no?

**Comment by ocefpaf** [comment]
> We should probably raise this as an issue instead of discussing in this PR, no?

Indeed. I was just curious if you would be interested in that path, if so we need a new issue.
(My comment on this PR was b/c it would change the nature of the changes here.)

**Pull request merged**
